version: "3.9"

services:
  tradingbot:
    build: .
    container_name: tradingbot
    restart: always
    expose:
      - "8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./shared:/app/shared
    env_file:
      - .env
    environment:
      - ENV=production
      - STRATEGY_NAME=ema_macd
      - SYMBOL=BTCUSDC
      - DATA_DIR=/app/data/strategies/btc
      - LOG_DIR=/app/logs/strategies/btc
      - BALANCE_DIR=/app/shared

  ethbot:
    build: .
    container_name: ethbot
    restart: always
    expose:
      - "8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./shared:/app/shared
    env_file:
      - .env
    environment:
      - ENV=production
      - STRATEGY_NAME=ema_macd
      - SYMBOL=ETHUSDC
      - DATA_DIR=/app/data/strategies/eth
      - LOG_DIR=/app/logs/strategies/eth
      - BALANCE_DIR=/app/shared

  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_BASE=/logs
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - tradingbot
      - ethbot
      - dozzle
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
